### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by jpeacock** [3dgroup/craftrest#1]
Hi,
I think I have it setup correctly, but I'm not sure how to effectively test it. Am I supposed to setup routes in the Craft admin, or?

```
return [
    'sections' => [
        'sectionHandleExample' => [
            'fields' => [
                'id'
            ],
            'extraFields' => [
                'myCustomFieldHandle'
            ],
            'prepareDataProvider' => function($model) {
                /** @var $query \craft\elements\Entry */
                $query = $model::find();

                return new \yii\data\ActiveDataProvider([
                    'query' => $query,
                ]);
            }
        ]
    ]
];
```

Trying to access mysite.com/api/ results in a 404 (a valid Craft 404 though, not a "template not found" error).

**Comment by 3dgroup** [comment]
I would love to say its anywhere near ready but it isn't and development has stopped for now. But if you wanted to look more into it, make sure you have created a folder called api in your route directory (with the same index.php and sever config files as the web directory) and then you will need your website server to point to the api folder with a sub domain. Then because you have a REST const the modules configs would use some custom routing settings and not use the traditional craft twig routing. You would then set what data you want and follow the REST api documents from Yii2.

**Comment by jpeacock** [comment]
Thanks! I'll check it out :)
